services:
  # database:
  #   image: postgres:16.4
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres/data:/var/lib/postgresql/data

  homecontrol-controller:
    # depends_on:
    #   - database
    build:
      context: ..
      dockerfile: homecontrol-controller/Dockerfile
    working_dir: /homecontrol-controller
    # See https://docs.astral.sh/uv/guides/integration/docker/#configuring-watch-with-docker-compose
    develop:
      watch:
        - action: sync
          path: .
          target: /homecontrol-controller/homecontrol_controller
    volumes:
      - ./database.db:/homecontrol-controller/database.db
    env_file: ".env"
    ports:
      - "8001:8000"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # network_mode: "host"
