[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "homecontrol-auth"
version = "0.1.0"
authors = [{ name = "2851999", email = "2851999@users.noreply.github.com" }]
description = "A REST API providing authentication for HomeControl."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "bcrypt>=5.0.0",
    "homecontrol-base-api",
    "pyjwt>=2.10.1",
]

[project.optional-dependencies]
dev = [
    "black>=25.11.0",
]

[tool.uv.sources]
homecontrol-base-api = { path = "../homecontrol-base-api" }

[tool.setuptools]
packages = ["homecontrol_auth"]
